### PR TITLE
Bug fixes 1.18.2

### LINKED ISSUE #285: Cannot craft ender eyes
development issue for issue #279 

## Expected Behavior

Bot makes blaze powder
Bot makes eyes of ender

## Actual Behavior (What lead to the bot getting permanently stuck)

Bot swaps between the tasks as it thinks that blaze powder is achieved before it actually is

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

` private Task getEyesOfEnderTask(AltoClef mod, int targetEyes) {
        if (mod.getEntityTracker().itemDropped(Items.ENDER_EYE)) {
            setDebugState("Picking up Dropped Eyes");
            return new PickupDroppedItemTask(Items.ENDER_EYE, targetEyes);
        }

        int eyeCount = mod.getItemStorage().getItemCount(Items.ENDER_EYE);

        int blazePowderCount = mod.getItemStorage().getItemCount(Items.BLAZE_POWDER); // THIS RETURNS 14 BEFORE THE CRAFTING IS COMPLETE
        int blazeRodCount = mod.getItemStorage().getItemCount(Items.BLAZE_ROD);
        int blazeRodTarget = (int)Math.ceil(((double)targetEyes - eyeCount - blazePowderCount) / 2.0);
        int enderPearlTarget = targetEyes - eyeCount;
        boolean needsBlazeRods = blazeRodCount < blazeRodTarget;
        boolean needsBlazePowder = eyeCount + blazePowderCount < targetEyes;
        boolean needsEnderPearls = mod.getItemStorage().getItemCount(Items.ENDER_PEARL) < enderPearlTarget;

        if (needsBlazePowder && !needsBlazeRods) {
            // We have enough blaze rods.
            setDebugState("Crafting blaze powder");
            return TaskCatalogue.getItemTask(Items.BLAZE_POWDER, targetEyes - eyeCount);
        }

        if (!needsBlazePowder && !needsEnderPearls) {
            // Craft ender eyes
            setDebugState("Crafting Ender Eyes");
            return TaskCatalogue.getItemTask(Items.ENDER_EYE, targetEyes);
        }//CAUSES CYCLING BETWEEN THESE TWO IF BLOCKS`

### LINKED ISSUE #286: Bot gets stuck if inventory full and withdraw from cooked furnace
## Steps to Reproduce (as best as you can)

cook a raw iron in a furnace so that iron_ingot is in the output slot
fill the bots inventory entirely with useless items
request the bot to get iron_ingot 1

## Expected Behavior

bot throws out un-needed item

## Actual Behavior

bot gets stuck

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### PR DESCRIPTION
**Pull request by JamesGreen31**
Okay some notes

custom task is already a PR so no need to have it here

this also includes a fix for @equip

Fixes #285 
Fixes #286

### CODE REVIEW

File: src/main/java/adris/altoclef/commands/EquipCommand.java [hunk 1]
```diff
@@ -12,7 +18,55 @@ public EquipCommand() throws CommandException {
 
     @Override
     protected void call(AltoClef mod, ArgParser parser) throws CommandException {
-        ItemTarget[] items = parser.get(ItemList.class).items;
-        mod.runUserTask(new EquipArmorTask(items), this::finish);
+        ItemTarget[] items;
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/commands/EquipCommand.java:21]: For the equip command

File: src/main/java/adris/altoclef/tasks/ResourceTask.java [hunk 2]
```diff
@@ -85,6 +85,16 @@ protected void onStart(AltoClef mod) {
 
     @Override
     protected Task onTick(AltoClef mod) {
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/tasks/ResourceTask.java:87]: This change needs reverted. I am not sure if the placement of this matters, but it should be at the end.

File: src/main/java/adris/altoclef/tasks/container/SmeltInFurnaceTask.java [hunk 3]
```diff
@@ -190,7 +192,13 @@ protected Task onTick(AltoClef mod) {
                 return new MoveInaccessibleItemToInventoryTask(_allMaterials);
             }
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/tasks/container/SmeltInFurnaceTask.java:194]: Furnace fix

File: src/main/java/adris/altoclef/tasks/speedrun/BeatMinecraft2Task.java [hunk 4]
```diff
@@ -577,9 +577,12 @@ private Task getEyesOfEnderTask(AltoClef mod, int targetEyes) {
         int blazeRodTarget = (int)Math.ceil(((double)targetEyes - eyeCount - blazePowderCount) / 2.0);
         int enderPearlTarget = targetEyes - eyeCount;
         boolean needsBlazeRods = blazeRodCount < blazeRodTarget;
-        boolean needsBlazePowder = eyeCount + blazePowderCount < targetEyes;
+        boolean needsBlazePowder =  eyeCount + blazePowderCount < targetEyes; // when this is wrong, we get stuck in an ender eye loop
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/tasks/speedrun/BeatMinecraft2Task.java:580]: I will adjust the comments after the merge, this is to help explain.

Ender eye fix

File: src/main/java/adris/altoclef/trackers/storage/InventorySubTracker.java [hunk 5]
```diff
@@ -119,6 +119,10 @@ private List<Slot> getSlotsThatCanFit(HashMap<Item, List<Slot>> list, ItemStack
                 if (airSlot.equals(CursorSlot.SLOT))
                     continue;
                 int windowCheck = airSlot.getWindowSlot();
+                // ignore 2x2 crafting grid -- it isn't meant for storage
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/trackers/storage/InventorySubTracker.java:122]: ender eye fix. We can't use 2x2 grid for storage

File: src/main/java/adris/altoclef/trackers/storage/InventorySubTracker.java [hunk 6]
```diff
@@ -213,13 +217,14 @@ private static boolean shouldIgnoreSlotForContainer(Slot slot) {
...
         //
-        // We also don't want our bot to think we "have" an item if it's in our armor/crafting/shield slots. That's annoying to work with.
+        // We also don't want our bot to think we "have" an item if it's in our armor/crafting output/shield slots.
         if (slot instanceof CraftingTableSlot && slot.equals(CraftingTableSlot.OUTPUT_SLOT))
             return true;
         if (slot instanceof PlayerSlot) {
             // Ignore non-normal inventory slots
             int window = slot.getWindowSlot();
-            return window < 9 || window > 44;
+            return window == 0 || (window > 4 && window < 9) || window > 44; // true if not a crafting input slot, or inventory slot.
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/trackers/storage/InventorySubTracker.java:226]: ender eye fix

we should count items that are in the 2x2 grid since they are in our inventory

File: src/main/java/adris/altoclef/trackers/storage/ItemStorageTracker.java [hunk 7]
```diff
@@ -1,18 +1,15 @@
...
 import adris.altoclef.trackers.TrackerManager;
 import adris.altoclef.util.ItemTarget;
 import adris.altoclef.util.helpers.StorageHelper;
-import adris.altoclef.util.slots.CraftingTableSlot;
-import adris.altoclef.util.slots.FurnaceSlot;
-import adris.altoclef.util.slots.PlayerSlot;
 import adris.altoclef.util.slots.Slot;
 import net.minecraft.item.Item;
 import net.minecraft.item.ItemStack;
+import net.minecraft.item.Items;
```
Comment (JamesGreen31) [inline src/main/java/adris/altoclef/trackers/storage/ItemStorageTracker.java:11]: these un-used imports can be removed. I will do that all in pre-merge cleanup

File: src/main/java/adris/altoclef/commands/EquipCommand.java (hunk 1 above)
Comment (JamesGreen31) [reply src/main/java/adris/altoclef/commands/EquipCommand.java:21]: remove this as it was just merged

**Comment by JamesGreen31** [comment]
Merge once checks compelte

**Review by JamesGreen31 — COMMENTED** [review]
Code ready for merge once checks are complete
